name: GitHub release

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        generateReleaseNotes: true
